#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"
echo "Running pre-push hook..."

# Apply Spotless formatting
echo "Applying code formatting with EsLint..."
npx eslint . --fix

echo "Pre-push checks passed."
